name: flightmap_gl_web
description: Web platform implementation of mapbox_gl
version: 0.8.0
homepage: https://github.com/Jungle-Works/flutter-flightmap-sdk

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  flightmap_gl_platform_interface: ^0.7.0
  mapbox_gl_dart: ^0.2.1
  image: '>=3.0.0 <5.0.0'

dependency_overrides:
  flightmap_gl_platform_interface:
    path: ../flightmap_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
